spring.application.name=estudos-mensageria
server.port=${server-port}

# Server Context Path
server.servlet.context-path=/mensageria
## SPRING DOC
# swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.show-common-extensions=true

## AWS
aws.accessKeyId=${id}
aws.secretKey=${key}
aws.region-name=${region}
aws.user-name=${user}
aws.sns.topicArn=arn:aws:sns:${region}:${user}:${topic-name}
aws.sqs.queue=${queue-name}

